### ISSUE TITLE
gem install 문서

### ISSUE THREAD

**Issue by sebayaki** [bootpay/server_ruby#1]
깃헙 메인에 있는것처럼 

```
gem 'bootpay'
```

이렇게 하면 
```
Could not find gem 'bootpay' in any of the gem sources listed in your Gemfile
```
에러가 납니다. rubygems.org 에 등록이 안되어있는것 같네요.
gemspec 파일을 보면 name 도 `bootpay` 가 아니라 `bootpay-rest-client` 로 되어있습니다.

현재는 
```
gem 'bootpay-rest-client', git: 'git@github.com:bootpay/server_ruby.git'
```

이렇게 해야 설치 가능하네요.

**Comment by Benjamin-Kang** [comment]
제안 주신 부분에 대한 readme를수정하였습니다.
package 명이 정해지기 전 readme를 작성해서 올바르지 않은 정보가 들어갔습니다. rubygems에는 몇차례 등록 요청을 했으나 문제가 발생되어 현재 등록을 취소한 상태입니다.
감사합니다.
